# Generated by Django 4.2.3 on 2023-07-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmember',
            options={'verbose_name': 'Сотрудник магазина', 'verbose_name_plural': 'Сотрудники магазина'},
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='courier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to='core.courier'),
        ),
    ]
