# Generated by Django 4.2.3 on 2023-07-12 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shopmember_options_alter_telegramuser_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='courier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to='core.courier'),
        ),
    ]
