# Generated by Django 4.2.3 on 2023-07-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='production_end',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='production_start',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='years',
            field=models.CharField(default=-42, max_length=30),
            preserve_default=False,
        ),
    ]
