# Generated by Django 4.2.3 on 2023-07-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Car brand', 'verbose_name_plural': 'Car brands'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car model', 'verbose_name_plural': 'Car models'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Courier', 'verbose_name_plural': 'Couriers'},
        ),
        migrations.AlterModelOptions(
            name='courierfeedback',
            options={'verbose_name': 'Courier Feedback', 'verbose_name_plural': 'Courier Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='ordercredential',
            options={'verbose_name': 'Order credential', 'verbose_name_plural': 'Order credentials'},
        ),
        migrations.AlterModelOptions(
            name='orderoffer',
            options={'verbose_name': 'Order offer', 'verbose_name_plural': 'Order offers'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='shopfeedback',
            options={'verbose_name': 'Shop Feedback', 'verbose_name_plural': 'Shop Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='shopmember',
            options={'verbose_name': 'Shop employee', 'verbose_name_plural': 'Shop employees'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram user', 'verbose_name_plural': 'Telegram users'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active.'), (1, 'Pending.'), (2, 'Done.')], default=0),
        ),
    ]
