# Generated by Django 4.2.3 on 2023-07-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carbrand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierfeedback',
            old_name='raiting',
            new_name='rating',
        ),
    ]
