# Generated by Django 4.2.3 on 2023-07-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carbrand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAvailableModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='courierfeedback',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='ordercredential',
            old_name='adress',
            new_name='address',
        ),
    ]
