# Generated by Django 4.2.3 on 2023-07-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carbrand_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='years',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='production_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='production_start',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
