# Generated by Django 4.2.3 on 2023-07-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopordersblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoffer',
            name='price',
            field=models.TextField(),
        ),
    ]
