# Generated by Django 4.2.3 on 2023-07-14 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopavailablemodels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercredential',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.courierfeedback'),
        ),
    ]
