# Generated by Django 4.2.3 on 2023-07-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_raiting_courierfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='credential',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.ordercredential'),
        ),
    ]
