# Generated by Django 4.2.3 on 2023-07-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercredential',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.courierfeedback'),
        ),
    ]
