# Generated by Django 4.2.3 on 2023-07-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderoffer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderoffer',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.orderoffer'),
        ),
        migrations.AlterField(
            model_name='orderoffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AlterField(
            model_name='orderoffer',
            name='price',
            field=models.IntegerField(),
        ),
    ]
