# Generated by Django 4.2.3 on 2023-07-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ordercredential_courier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderoffer',
            options={'verbose_name': 'Заявка на заказ', 'verbose_name_plural': 'Заявки на заказ'},
        ),
        migrations.AlterField(
            model_name='courierfeedback',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Активно'), (1, 'В ожидание'), (2, 'Готово')], default=0),
        ),
        migrations.AlterField(
            model_name='shopfeedback',
            name='raiting',
            field=models.PositiveIntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)], default=0),
        ),
    ]
