# Generated by Django 4.2.3 on 2023-07-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_orderoffer_is_approved_order_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.orderoffer'),
        ),
    ]
