# Generated by Django 4.2.3 on 2023-07-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ordercredential_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoffer',
            name='price',
            field=models.FloatField(),
        ),
    ]
