# Generated by Django 4.2.3 on 2023-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ordercredential_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierregistrationcode',
            name='user',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderoffer',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
