# Generated by Django 4.2.3 on 2023-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_courierregistrationcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistrationcode',
            name='user',
            field=models.BigIntegerField(null=True),
        ),
    ]
