# Generated by Django 4.2.3 on 2023-07-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_orderoffer_price'),
        ('core', '0016_messagetodelete'),
    ]

    operations = [
    ]
