# Generated by Django 4.2.3 on 2023-08-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ordercredential_lat_ordercredential_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
                ('msg_id', models.BigIntegerField(default=None, null=True)),
            ],
        ),
    ]
