# Generated by Django 4.2.3 on 2023-08-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_messagetoedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.courier')),
            ],
        ),
        migrations.AddField(
            model_name='ordercredential',
            name='courier_offer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.courieroffer'),
        ),
    ]
