# Generated by Django 4.2.3 on 2023-08-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_courieroffer_ordercredential_courier_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courieroffer',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
            preserve_default=False,
        ),
    ]
