# Generated by Django 4.2.3 on 2023-09-07 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_courieroffer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('days', models.BigIntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='subscribe_till',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='ordercredential',
            name='courier_offer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.courieroffer'),
        ),
        migrations.AlterField(
            model_name='ordercredential',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
